--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.3.8
target Corona SDK
extension lua
exportName sheet
exportPath file:///Users/mugen/Desktop/prog/corona/support_spriteloq/pjrich/reoddpositioningofassetswhenpackingseveralswfs
sheetSize 1257x1185
sources 4
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; xScale; yScale
Amber; Amber.swf; (x=0, y=0); 1; 6; 12; (x=-162, y=-197); (x=166, y=95); (x=-164, y=-199, w=332, h=296); 0; 1; 1
Rex; Rex.swf; (x=0, y=0); 1; 6; 12; (x=-150, y=-151); (x=234, y=125); (x=-152, y=-153, w=388, h=280); 0; 1; 1
Ruby; Ruby.swf; (x=0, y=0); 1; 6; 12; (x=-123, y=-233); (x=189, y=114); (x=-125, y=-235, w=316, h=351); 0; 1; 1
Spike; Spike.swf; (x=0, y=0); 1; 6; 12; (x=-136, y=-109); (x=166, y=81); (x=-138, y=-111, w=306, h=194); 0; 1; 1
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 1500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["Amber"] = {
        {
            name="Amber-1",
            spriteColorRect={x=32, y=102},
            textureRect={x=0, y=826, width=266, height=194},
            spriteSourceSize={width=332, height=296},
            spriteTrimmed=true,
        },
        {
            name="Amber-2",
            spriteColorRect={x=33, y=68},
            textureRect={x=959, y=578, width=288, height=227},
            spriteSourceSize={width=332, height=296},
            spriteTrimmed=true,
        },
        {
            name="Amber-3",
            spriteColorRect={x=20, y=33},
            textureRect={x=312, y=316, width=312, height=262},
            spriteSourceSize={width=332, height=296},
            spriteTrimmed=true,
        },
        {
            name="Amber-4",
            spriteColorRect={x=0, y=0},
            textureRect={x=210, y=0, width=299, height=295},
            spriteSourceSize={width=332, height=296},
            spriteTrimmed=true,
        },
        {
            name="Amber-5",
            spriteColorRect={x=19, y=34},
            textureRect={x=0, y=316, width=312, height=262},
            spriteSourceSize={width=332, height=296},
            spriteTrimmed=true,
        },
        {
            name="Amber-6",
            spriteColorRect={x=33, y=68},
            textureRect={x=670, y=578, width=289, height=228},
            spriteSourceSize={width=332, height=296},
            spriteTrimmed=true,
        }
    }
    allFrames = table.copy(allFrames, frameSets["Amber"])

    frameSets["Rex"] = {
        {
            name="Rex-1",
            spriteColorRect={x=0, y=30},
            textureRect={x=624, y=316, width=303, height=250},
            spriteSourceSize={width=388, height=280},
            spriteTrimmed=true,
        },
        {
            name="Rex-2",
            spriteColorRect={x=168, y=30},
            textureRect={x=0, y=578, width=209, height=248},
            spriteSourceSize={width=388, height=280},
            spriteTrimmed=true,
        },
        {
            name="Rex-3",
            spriteColorRect={x=128, y=27},
            textureRect={x=997, y=0, width=260, height=252},
            spriteSourceSize={width=388, height=280},
            spriteTrimmed=true,
        },
        {
            name="Rex-4",
            spriteColorRect={x=128, y=0},
            textureRect={x=769, y=0, width=228, height=278},
            spriteSourceSize={width=388, height=280},
            spriteTrimmed=true,
        },
        {
            name="Rex-5",
            spriteColorRect={x=128, y=24},
            textureRect={x=997, y=0, width=260, height=252},
            spriteSourceSize={width=388, height=280},
            spriteTrimmed=true,
        },
        {
            name="Rex-6",
            spriteColorRect={x=169, y=26},
            textureRect={x=209, y=578, width=210, height=248},
            spriteSourceSize={width=388, height=280},
            spriteTrimmed=true,
        }
    }
    allFrames = table.copy(allFrames, frameSets["Rex"])

    frameSets["Ruby"] = {
        {
            name="Ruby-1",
            spriteColorRect={x=0, y=119},
            textureRect={x=419, y=578, width=251, height=232},
            spriteSourceSize={width=316, height=351},
            spriteTrimmed=true,
        },
        {
            name="Ruby-2",
            spriteColorRect={x=14, y=67},
            textureRect={x=927, y=316, width=302, height=249},
            spriteSourceSize={width=316, height=351},
            spriteTrimmed=true,
        },
        {
            name="Ruby-3",
            spriteColorRect={x=56, y=31},
            textureRect={x=509, y=0, width=260, height=285},
            spriteSourceSize={width=316, height=351},
            spriteTrimmed=true,
        },
        {
            name="Ruby-4",
            spriteColorRect={x=81, y=0},
            textureRect={x=0, y=0, width=210, height=316},
            spriteSourceSize={width=316, height=351},
            spriteTrimmed=true,
        },
        {
            name="Ruby-5",
            spriteColorRect={x=56, y=31},
            textureRect={x=509, y=0, width=260, height=285},
            spriteSourceSize={width=316, height=351},
            spriteTrimmed=true,
        },
        {
            name="Ruby-6",
            spriteColorRect={x=14, y=67},
            textureRect={x=927, y=316, width=302, height=249},
            spriteSourceSize={width=316, height=351},
            spriteTrimmed=true,
        }
    }
    allFrames = table.copy(allFrames, frameSets["Ruby"])

    frameSets["Spike"] = {
        {
            name="Spike-1",
            spriteColorRect={x=0, y=28},
            textureRect={x=876, y=826, width=276, height=166},
            spriteSourceSize={width=306, height=194},
            spriteTrimmed=true,
        },
        {
            name="Spike-2",
            spriteColorRect={x=1, y=29},
            textureRect={x=0, y=1020, width=296, height=165},
            spriteSourceSize={width=306, height=194},
            spriteTrimmed=true,
        },
        {
            name="Spike-3",
            spriteColorRect={x=1, y=14},
            textureRect={x=571, y=826, width=305, height=180},
            spriteSourceSize={width=306, height=194},
            spriteTrimmed=true,
        },
        {
            name="Spike-4",
            spriteColorRect={x=1, y=0},
            textureRect={x=266, y=826, width=305, height=194},
            spriteSourceSize={width=306, height=194},
            spriteTrimmed=true,
        },
        {
            name="Spike-5",
            spriteColorRect={x=1, y=13},
            textureRect={x=571, y=826, width=305, height=180},
            spriteSourceSize={width=306, height=194},
            spriteTrimmed=true,
        },
        {
            name="Spike-6",
            spriteColorRect={x=2, y=28},
            textureRect={x=296, y=1020, width=296, height=164},
            spriteSourceSize={width=306, height=194},
            spriteTrimmed=true,
        }
    }
    allFrames = table.copy(allFrames, frameSets["Spike"])


    sheet = sprite.newSpriteSheetFromData("sheet.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "Amber", 1, 6, 12, 0, 0 - (332/2 + -164), 0 - (296/2 + -199), 332, 296, 32, 102, 266, 194, frameSets["Amber"], false)
    newSpriteSet(sheet, "Rex", 7, 6, 12, 0, 0 - (388/2 + -152), 0 - (280/2 + -153), 388, 280, 0, 30, 303, 250, frameSets["Rex"], false)
    newSpriteSet(sheet, "Ruby", 13, 6, 12, 0, 0 - (316/2 + -125), 0 - (351/2 + -235), 316, 351, 0, 119, 251, 232, frameSets["Ruby"], false)
    newSpriteSet(sheet, "Spike", 19, 6, 12, 0, 0 - (306/2 + -138), 0 - (194/2 + -111), 306, 194, 0, 28, 276, 166, frameSets["Spike"], false)

    local shapes = {}
    shapes["Amber"] = {

    }
    shapes["Rex"] = {

    }
    shapes["Ruby"] = {

    }
    shapes["Spike"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
