module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:6f39d15b3a5d753d2dd7600e41afb6d3$
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "walking e0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking e0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking e0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking e0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking e0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking e0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking e0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking e0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 0, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking n0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 128, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking ne0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 256, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking nw0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 384, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking s0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 512, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking se0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 640, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking sw0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 768, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0000.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 0, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0001.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 128, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0002.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 256, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0003.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 384, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0004.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 512, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0005.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 640, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0006.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 768, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "walking w0007.bmp",
                spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
                textureRect = { x = 896, y = 896, width = 128, height = 128 },
                spriteSourceSize = { width = 128, height = 128 },
                spriteTrimmed = false,
                textureRotated = false
            },
        }
    }
    return sheet
end

